# Release drafter configuration https://github.com/release-drafter/release-drafter#configuration
# Emojis were chosen to match the https://gitmoji.carloscuesta.me/

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "💡 Question"
    labels: [question]
  - title: "💬 Additional Content"
    labels: [documentation]

template: |
  ## What’s Changed

  $CHANGES
